#name: 🐛 Bug Report
#description: Report a bug to help us improve eMark
#title: "[BUG] "
#labels: ["bug"]
#body:
#  - type: input
#    id: description
#    attributes:
#      label: Bug Description
#      description: Describe the bug in detail.
#      placeholder: What went wrong?
#    validations:
#      required: true
#
#  - type: textarea
#    id: steps
#    attributes:
#      label: Steps to Reproduce
#      description: Step-by-step guide to reproduce the issue.
#      placeholder: "1. Go to...\n2. Click...\n3. See error..."
#    validations:
#      required: true
#
#  - type: dropdown
#    id: severity
#    attributes:
#      label: Severity Level
#      description: How severe is this bug?
#      options:
#        - Low
#        - Medium
#        - High
#    validations:
#      required: true



name: 🐛 Bug Report
description: Report a bug to help us improve eMark
title: "[BUG] "
labels: ["bug"]
body:
  - type: input
    id: description
    attributes:
      label: Bug Description
      description: Briefly describe the issue.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step guide to reproduce the issue.
      placeholder: "1. Go to...\n2. Click...\n3. See error..."
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Logs
      description: If applicable, add screenshots or logs.
      placeholder: Drag & drop or paste images here.

  - type: input
    id: version
    attributes:
      label: eMark Version
      placeholder: e.g. v1.0.3
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this bug?
      options:
        - Low
        - Medium
        - High
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked existing issues.
        - label: I can reproduce this issue consistently.
