name: 🐛 Bug Report
description: Report a bug to help us improve eMark
title: "[BUG] "
labels: ["bug"]
body:
  - type: input
    id: description
    attributes:
      label: Bug Description
      description: Describe the bug in detail.
      placeholder: What went wrong?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Step-by-step guide to reproduce the issue.
      placeholder: "1. Go to...\n2. Click...\n3. See error..."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this bug?
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
