#name: ✨ Feature Request
#description: Suggest an idea for eMark
#title: "[Feature] "
#labels: ["enhancement"]
#body:
#  - type: input
#    id: description
#    attributes:
#      label: Feature Description
#      description: What feature would you like to see?
#      placeholder: Short summary of the feature.
#    validations:
#      required: true
#
#  - type: textarea
#    id: benefit
#    attributes:
#      label: Use Case / Benefit
#      description: How will this feature help you or others?
#      placeholder: Explain why this feature is useful.
#    validations:
#      required: true



name: ✨ Feature Request
description: Suggest an idea for eMark
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: input
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: Short summary of the feature.
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Use Case / Benefit
      description: How will this feature help you or others?
      placeholder: Explain why this feature is useful.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: If you have an idea how it should work, describe it here.
      placeholder: Describe suggested approach or UI.

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      placeholder: Did you consider other approaches or tools?

  - type: textarea
    id: screenshots
    attributes:
      label: Additional Context / Mockups
      placeholder: Add screenshots, UI sketches, or references if helpful.

  - type: input
    id: version
    attributes:
      label: eMark Version
      placeholder: e.g. v1.0.3

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked existing issues and discussions.
        - label: This feature request is not a duplicate.
