name: ✨ Feature Request
description: Suggest an idea for eMark
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: input
    id: description
    attributes:
      label: Feature Description
      description: What feature would you like to see?
      placeholder: Short summary of the feature.
    validations:
      required: true

  - type: textarea
    id: benefit
    attributes:
      label: Use Case / Benefit
      description: How will this feature help you or others?
      placeholder: Explain why this feature is useful.
    validations:
      required: true
